name: Compile Libraries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-libs-linux-loongarch64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
      fail-fast: true

    steps:
      - name: Install loongarch64-linux-gnu cross-compiler
        run: |
          apt-get update
          apt-get install -y build-essential \
                             curl \
                             python3 \
                             g++-14-loongarch64-linux-gnu \
                             pkg-config
      - uses: actions/checkout@v4
      - name: Compile library
        run: |
          export CONFIGURE_FLAGS="--host=loongarch64-linux-gnu \
                                  --build=x86_64-linux-gnu \
                                  CC=loongarch64-linux-gnu-gcc-14 \
                                  CXX=loongarch64-linux-gnu-g++-14"
          wget -qO - https://raw.githubusercontent.com/Loongson-Cloud-Community/libsndfile-binaries/refs/heads/dev/linux-build-add-loong64-support.patch | patch -p1
          ./linux_build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: lib-linux-loongarch64
          path: "libsndfile_loongarch64.so"
